# Generated by Django 2.1.7 on 2019-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1_input', models.CharField(max_length=200)),
                ('var_2_input', models.CharField(max_length=200)),
                ('num_permutations', models.CharField(max_length=200)),
            ],
        ),
    ]
