# Generated by Django 2.1.7 on 2019-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadahead_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtestmodel',
            name='var_1_input',
            field=models.CharField(max_length=2000),
        ),
    ]
