# Generated by Django 2.1.7 on 2019-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadahead_app', '0002_auto_20190427_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtestmodel',
            name='var_1_input',
            field=models.CharField(max_length=200),
        ),
    ]
