# Generated by Django 2.1.7 on 2019-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadahead_app', '0003_auto_20190427_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtestmodel',
            name='var_1_input',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='abtestmodel',
            name='var_2_input',
            field=models.CharField(max_length=10000),
        ),
    ]
