# Generated by Django 2.1.7 on 2019-05-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadahead_app', '0004_auto_20190427_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtestmodel',
            name='ttest_equal_var',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
