# Generated by Django 2.1.7 on 2019-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadahead_app', '0005_abtestmodel_ttest_equal_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word2VecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_1', models.CharField(max_length=255)),
                ('term_2', models.CharField(max_length=255)),
                ('corpus', models.CharField(choices=[('FB_COMMON', 'Facebook Common Crawl 600B'), ('FB_WIKI', 'English Wikipedia 2017 16B'), ('GOGGLE_NEWS', 'Google News 100B'), ('NYT', 'New York Times Article Snippets 2000 - 2019 ')], default=None, max_length=11, null=True)),
            ],
        ),
    ]
